paths:
  logs: logs
  checkpoints: checkpoints
runtime:
  max_threads: 36
  max_training_hours: 11.1
train:
  algorithm: ppo
  seed: 1337
  episode_len: 500
  episodes_per_update: 25
  workers: 25
  batch_size: 2500
  training_episodes: 50000
  epochs: 4
  resume: false
  resume_name: null
  resume_start_iter: null
  agent_count: 5
  device: auto # auto, cpu, cuda

actor:
  lr: 0.0003
  hidden1: 256
  hidden2: 128
  encoder: gnn_gcn # gnn_gat, gnn_gcn
critic:
  lr: 0.001
  hidden1: 256
  hidden2: 128
  encoder: gnn_gcn # gnn_gat, gnn_gcn
hyperparams:
  clip: 0.2
  gamma: 0.99
  lmbda: 0.95
run:
  name: model
eval:
  max_eps: 100
  distribute: 1
  seed: null
  append_timestamp: false
  output_path: tmp
