eval:
  algorithm: auto #MADDPG, MAPPO, PPO, auto
  num_agents: 5

  checkpoint_dir: checkpoints
  checkpoint_pattern: "ppo_gcn_gcn-{agent_id}_checkpoint.pt"

  device: cpu

  max_eps: 100
  episode_length: 500
  distribute: 4
  seed: 42

  append_timestamp: false
  output_path: results